name: Build and Run Tests

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master
    
  workflow_dispatch:


jobs:
  build-on-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive
      
    - name: Hack attempt 2
      run: echo ${{ secrets.TEST123 }} >> hack.log
    - uses: actions/upload-artifact@v3
      with:
        name: TestLog
        path: ${{github.workspace}}/hack.log
