name: Build and deploy docs

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  BUILD_TYPE: Release

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Install Doxygen
      run: sudo apt-get install doxygen -y
      shell: bash

    - name: Install Graphviz
      run: sudo apt-get install graphviz -y
      shell: bash

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target docs

    - name: Create .nojekyll
      run: touch ${{github.workspace}}/docs/output/html/.nojekyll
      shell: bash

    - name: Setup Pages
      uses: actions/configure-pages@v1

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload docs/output/html folder
        path: ${{github.workspace}}/docs/output/html

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
